# Generated by Django 5.2.8 on 2025-12-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, unique=True, verbose_name="Заголовок")),
                ("text", models.TextField(blank=True, null=True, verbose_name="Содержимое")),
                ("image", models.ImageField(blank=True, null=True, upload_to="photos/", verbose_name="Изображение")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("published", models.BooleanField(default=False, verbose_name="Признак публикации")),
                ("views", models.ImageField(upload_to="", verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "блог",
                "verbose_name_plural": "блоги",
                "ordering": ["views"],
            },
        ),
    ]
