# Generated by Django 5.2.8 on 2025-12-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="views",
            field=models.ImageField(default=0, upload_to="", verbose_name="Количество просмотров"),
        ),
    ]
