# Generated by Django 5.2.8 on 2025-12-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_blog_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="views",
            field=models.IntegerField(default=0, verbose_name="Количество просмотров"),
        ),
    ]
