# Generated by Django 5.2.8 on 2025-12-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_alter_blog_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="viewed_100_times",
            field=models.BooleanField(default=False),
        ),
    ]
