# Generated by Django 5.2.8 on 2025-12-02 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category_name", models.CharField(max_length=150, unique=True, verbose_name="Наименование")),
                ("description", models.CharField(max_length=150, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "ordering": ["category_name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_name", models.CharField(max_length=150, unique=True, verbose_name="Наименование")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
                ("product_image", models.ImageField(upload_to="photos/", verbose_name="Изображение")),
                ("price", models.FloatField(verbose_name="Цена за покупку")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="Дата последнего изменения")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="products", to="catalog.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "ordering": ["product_name"],
            },
        ),
    ]
