# Generated by Django 5.2.8 on 2025-12-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country", models.CharField(max_length=150, verbose_name="Страна")),
                ("inn", models.CharField(max_length=11, verbose_name="ИНН")),
                ("address", models.TextField(verbose_name="Адрес")),
            ],
            options={
                "verbose_name": "Контакты",
            },
        ),
    ]
