# Generated by Django 5.2.8 on 2025-12-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contacts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contacts",
            options={"verbose_name": "Контакты", "verbose_name_plural": "Контакты"},
        ),
        migrations.AlterField(
            model_name="contacts",
            name="inn",
            field=models.CharField(max_length=12, verbose_name="ИНН"),
        ),
    ]
