# Generated by Django 5.2.8 on 2025-12-04 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_contacts_options_alter_contacts_inn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(
                default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name="Цена за покупку"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(blank=True, null=True, upload_to="photos/", verbose_name="Изображение"),
        ),
    ]
