# Generated by Django 5.2.8 on 2025-12-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_price_alter_product_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Имя")),
                ("phone", models.IntegerField(max_length=11, unique=True, verbose_name="Телефон")),
                ("message", models.TextField(blank=True, null=True, verbose_name="Сообщение")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
    ]
