# Generated by Django 5.2.8 on 2025-12-08 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_customerdata_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerdata",
            name="phone",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Введите корректный номер телефона (например: +79157013843, 8-915-701-38-43)",
                        regex="^(\\+?7|8)[\\s\\-]?\\(?\\d{3}\\)?[\\s\\-]?\\d{3}[\\s\\-]?\\d{2}[\\s\\-]?\\d{2}$",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
    ]
