# Generated by Django 5.2.8 on 2025-12-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_customerdata_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerdata",
            options={"verbose_name": "Покупатель", "verbose_name_plural": "Покупатели"},
        ),
        migrations.AlterField(
            model_name="customerdata",
            name="phone",
            field=models.CharField(max_length=20, unique=True, verbose_name="Телефон"),
        ),
    ]
