# Generated by Django 5.2.8 on 2025-12-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_customerdata_options_alter_customerdata_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(default=0.0, verbose_name="Цена за покупку"),
        ),
    ]
